MvcApp/Controllers/SysUserController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using System.Data;
using System.Data.OleDb;
using NHibernate.Criterion;
using com.fxm.MVCHibernate.Domain;
using com.fxm.MVCHibernate.Service;
using com.fxm.MVCHibernate.Core;
using System.Web;

namespace MvcApp.Controllers
{
    public class SysUserController : UcController
    {
        #region 列表
        public ActionResult Index(int pageIndex = 1, string JobNumber = "")
        {
            int count = 0;//记录数
            IList<ICriterion> listQuery = new List<ICriterion>();
            if (JobNumber.Length > 0)
            {
                listQuery.Add(Expression.Eq("LoginCode", JobNumber));
            }
            IList<Order> listOrder = new List<Order>() { new Order("ID", true) };
            IList<SysUser> list = Container.Instance.Resolve<IServiceSysUser>().Qry(listQuery, listOrder, pageIndex, PagerHelper.PageSize, out count);
            //转换为PageList集合，用于分页控件显示不同的页码
            PageList<SysUser> pageList = list.ToPageList<SysUser>(pageIndex, PagerHelper.PageSize, count);
            //用pageList集合填充页面
            return View(pageList);
        }
        #endregion

        #region 明细
        public ActionResult Details(int id)
        {
            //根据id获取实体
            SysUser user = Container.Instance.Resolve<IServiceSysUser>().GetEntity(id);
            //用户所属角色
            ViewBag.cblItems = AppHelper.InitCheckBoxList(Container.Instance.Resolve<IServiceSysRole>().GetAll(), user.SysRoleList);
            return View(user);
        }
        #endregion

        #region 登录
        public ViewResult Login()
        {
            if (AppHelper.IsMobileBrowser)
            {
                return View("LoginMobile");
            }
            else
            {
                return View("Login");
            }
        }
        /// <summary>
        /// 验证登录
        /// </summary>
        /// <param name="account">账户名</param>
        /// <param name="password">密码</param>
        /// <returns></returns>
        [HttpPost]
        public string Login(string account, string password = "123")
        {
            //访问数据库，根据用户名和密码获取用户信息
            IList<ICriterion> listQuery = new List<ICriterion>() { 
                Expression.Eq("LoginCode", account), 
                Expression.Eq("Password", AppHelper.EncodeMd5(password)), 
                Expression.Eq("Status", 0) };
            IList<SysUser> lst = Container.Instance.Resolve<IServiceSysUser>().Qry(listQuery);
            if (lst.Count > 0)
            {
                AppHelper.LoginedUser = lst[0];//保存用户登录信息
                if (AppHelper.IsMobileBrowser)
                {
                    if (account.Substring(0, 2).ToLower() == "hk")
                    {
                        return AppHelper.Host + "Home/IndexMobile";
                    }
                    else
                    {
                        return AppHelper.Host + "Home/IndexDriverMobile";
                    }
                }
                else
                {
                    return AppHelper.Host + "Home/Index";
                }
            }
            else
            {
                return "0";
            }
        }
        /// <summary>
        /// 退出登录
        /// </summary>
        public ViewResult ExitLogin()
        {
            Session.Clear();

            return View("Login");
        }
        #endregion

        #region 新增
        public ActionResult Create()
        {
            SysUser entity = new SysUser();
            entity.Status = 0;


            InitItems(entity);
            return View(entity);
        }
        [HttpPost]
        public ActionResult Create(SysUser entity, string roleIDs)
        {
            try
            {
                entity.SysRoleList = Container.Instance.Resolve<IServiceSysRole>().Qry(new List<ICriterion>() { Expression.In("ID", AppHelper.StrToArray(roleIDs)) });
                entity.Password = AppHelper.EncodeMd5(entity.Password);

                Container.Instance.Resolve<IServiceSysUser>().Add(entity);

                return RedirectToAction("Index");
            }
            catch
            {
                InitItems(entity);
                return View(entity);
            }
        }
        #endregion

        #region 删除
        public ActionResult Delete(int id)
        {
            Container.Instance.Resolve<IServiceSysUser>().Del(id);
            return RedirectToAction("Index");
        }
        #endregion

        #region 修改
        public ActionResult Edit(int id)
        {
            SysUser entity = Container.Instance.Resolve<IServiceSysUser>().GetEntity(id);

            InitItems(entity);
            return View(entity);
        }
        [HttpPost]
        public ActionResult Edit(SysUser entity, string roleIDs)
        {
           try
            {
                entity.SysRoleList = Container.Instance.Resolve<IServiceSysRole>().Qry(new List<ICriterion>() { Expression.In("ID", AppHelper.StrToArray(roleIDs)) });

                Container.Instance.Resolve<IServiceSysUser>().Upt(entity);

                return RedirectToAction("Index");
            }
           catch
           {
               InitItems(entity);
               return View(entity);
           }
        }
        #endregion

        #region 更改用户状态
        public ActionResult SwitchStatus(int id)
        {
            SysUser entity = Container.Instance.Resolve<IServiceSysUser>().GetEntity(id);
            entity.Status = (entity.Status == 0) ? 1 : 0;

            Container.Instance.Resolve<IServiceSysUser>().Upt(entity);//更新当前用户

            return RedirectToAction("Index");
        }
        #endregion

        #region   修改密码
        public ActionResult ChangePassword()
        {
            if (AppHelper.IsMobileBrowser)
            {
                return View("ChangePasswordMobile", AppHelper.LoginedUser);
            }
            else
            {
                return View("ChangePassword", AppHelper.LoginedUser);
            }
        }
        [HttpPost]
        public ActionResult ChangeNewPassword(string password)
        {
            SysUser entity = Container.Instance.Resolve<IServiceSysUser>().GetEntity(AppHelper.LoginedUser.ID);

            entity.Password = AppHelper.EncodeMd5(password);
            Container.Instance.Resolve<IServiceSysUser>().Upt(entity);

            AppHelper.LoginedUser.Password = entity.Password;

            return Json(true, JsonRequestBehavior.AllowGet);
        }

        public ActionResult PasswordCheck(string oldPasswod = "")
        {
            return Json(AppHelper.EncodeMd5(oldPasswod) == AppHelper.LoginedUser.Password, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region 导入Excel
        [HttpPost]
        public ActionResult ImportExcel()
        {
            JsonResult json = new JsonResult();
            try
            {
                HttpPostedFileBase fb = Request.Files[0];
                string fileName = fb.FileName;  //获取到文件名  xx.xls
                fb.SaveAs(Server.MapPath("~/Content/Model.xls"));

                string file = Server.MapPath("~/Content/Model.xls");
                string strConn = "Provider=Microsoft.Jet.OLEDB.4.0;" + "Data Source=" + file + ";" + "Extended Properties=Excel 8.0;";
                OleDbDataAdapter odda = new OleDbDataAdapter("select * from [Sheet1$]", strConn);
                DataSet myds = new DataSet();
                odda.Fill(myds, "ExcelInfo");

                DataTable dt = myds.Tables["ExcelInfo"].DefaultView.ToTable();
                foreach (DataRow dr in dt.Rows)
                {
                    if (dr["工号"].ToString().Length > 0)
                    {
                        IList<SysUser> lst = Container.Instance.Resolve<IServiceSysUser>().Qry(new List<ICriterion>() { Expression.Eq("LoginCode", dr["工号"].ToString()) });
                        if (lst.Count > 0)
                        {
                            SysUser entity = Container.Instance.Resolve<IServiceSysUser>().GetEntity(lst[0].ID);
                            entity.LoginCode = dr["工号"].ToString();
                            entity.Password = AppHelper.EncodeMd5(dr["初始密码"].ToString());
                            entity.Status = 0;
                            entity.Name = dr["姓名"].ToString();
                            entity.SysRoleList = new List<SysRole>() { com.fxm.MVCHibernate.Core.Container.Instance.Resolve<IServiceSysRole>().GetEntity(2) };

                            Container.Instance.Resolve<IServiceSysUser>().Upt(entity);
                        }
                        else
                        {
                            com.fxm.MVCHibernate.Core.Container.Instance.Resolve<IServiceSysUser>().Add(new SysUser()
                            {
                                LoginCode = dr["工号"].ToString(),
                                Password = AppHelper.EncodeMd5(dr["初始密码"].ToString()),
                                Status = 0,
                                Name = dr["姓名"].ToString(),
                                SysRoleList = new List<SysRole>() { com.fxm.MVCHibernate.Core.Container.Instance.Resolve<IServiceSysRole>().GetEntity(2) }
                            });
                        }
                    }
                }
                json.Data = "导入成功";
            }
            catch (System.Exception ex)
            {

                json.Data = "导入失败!" + ex.Message;
            }
            return View("Index");
        }
        #endregion

        private void InitItems(SysUser entity)
        {
            //角色
            ViewBag.cblItems = AppHelper.InitCheckBoxList(Container.Instance.Resolve<IServiceSysRole>().GetAll(), entity.SysRoleList);
            //状态
            ViewBag.statusItems = new List<SelectListItem>() { 
                new SelectListItem { Text = "正常", Value = "0",Selected=(entity.Status == 0) },

MvcApp/Views/SysUser/ChangePassword.cshtml
@model com.fxm.MVCHibernate.Domain.SysUser

@{
    ViewBag.Title = "更改密码";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script language="javascript" type="text/javascript">
    $(document).ready(function() {
        var changeOldpass = 1;
        var changeNewPw = 1;
        $("#OldPassword").change(function() {
            var oldPW = $("#OldPassword").val();
            var url = '@Url.Action("PasswordCheck", "SysUser")' + "?r=" + Math.random();
            $.get(url, { "oldPasswod": oldPW }, function(Check) {
                if (Check) {
                    $("#Show").html("<img src='../../Content/Img/btnOk.png' style=' height:19px; padding-bottom:0px;' />");
                    changeOldpass = 2;
                } else {
                    $("#Show").html("<img src='../../Content/Img/btnClose.png' style=' height:19px; padding-bottom:0px;'/>密码错误");
                }
            }, "json");
        })

        $("#password2").change(function() {
            var PW1 = $("#password1").val();
            var PW2 = $("#password2").val();
            if (PW1 == PW2) {
                $("#PWshow").html("<img src='../../Content/Img/btnOk.png' style=' height:19px; padding-bottom:0px;' />");
                changeNewPw = 3;
            } else {
                $("#PWshow").html("<img src='../../Content/Img/btnClose.png' style=' height:19px; padding-bottom:0px;'/>密码不一致");
            }
        });

        $("#BtnSave").click(function() {
            var PW = $("#password2").val();
            if (changeOldpass == 2 && changeNewPw == 3) {
                var url = '@Url.Action("ChangeNewPassword", "SysUser")' + "?R=" + Math.random();
                var data = { "password": PW };
                $.post(url, data, function(Check) {
                    if (Check) {
                        $("#ShowPWC").html("密码修改成功");
                    } else {
                        $("#ShowPWC").html("密码修改失败"); //失败不提示
                    }
                }, "json");
            }
        });
    });
    $(document).ready(function() {
        $("#BtnClear").click(function() {
            $("#OldPassword").val("");
            $("#password1").val("");
            $("#password2").val("");
        });
    });


    $(document).ready(function() {
        $("#aa").click(function() {
            location.href = "http://baidu.com";
        });
    });

</script>
<table cellspacing="0" cellpadding="0" style="vertical-align: top; width: 100%; border: 0;">
    <tr>
        <td class="contentPageTitle" style="text-align: center; vertical-align: middle">
            修改密码
        </td>
    </tr>
    <tr>
        <td class="titleContentDivider"></td>
    </tr>
    <tr>
        <td height="30">
            <input class="btn3" type="button" value="确认" id="BtnSave" />
            <input class="btn3" type="button" value="重置" id="BtnClear" />
    </tr>
    <tr>
        <td>
            <fieldset>
                <legend></legend>
                <div class="editor-label-width">
                    @Html.LabelFor(model => model.Name)：
                </div>
                <div class="editor-field">
                    @Html.DisplayFor(m => m.Name)
                </div>
                <div class="editor-label-width">
                    @Html.LabelFor(model => model.LoginCode)：
                </div>
                <div class="editor-field">
                    @Html.DisplayFor(m => m.LoginCode)
                </div>
                <div class="editor-label-width">
                    原密码：
                </div>
                <div class="editor-field">
                    @Html.Password("OldPassword", "")
                    <span id="Show"></span>
                </div>
                <div class="editor-label-width">
                    新密码：
                </div>
                <div class="editor-field">
                    @Html.Password("password1", "")
                </div>
                <div class="editor-label-width">
                    确认密码：
                </div>
                <div class="editor-field">
                    @Html.Password("password2", "")<span id="PWshow"></span>
                </div>
                <div style="margin-left: 200px;">
                    <br />
                </div>
                <div id="ShowPWC">
                </div>
            </fieldset>
        </td>
    </tr>
</table>

MvcApp/Views/SysUser/ChangePasswordMobile.cshtml
@model com.fxm.MVCHibernate.Domain.SysUser

@{
    ViewBag.Title = "更改密码";
    Layout = "~/Views/Shared/_LayoutMobile.cshtml";
}
<!-- 导航 -->
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">重庆惠科金渝光电班车订座系统 </a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="/Home/IndexMobile">首页</a></li>
                <li><a href="/OrderSeatRec/CarListForOrder">订座</a></li>
                <li><a href="/OrderSeatRec/QryPersonal">我的乘车记录</a></li>
                <li class="active"><a href="/SysUser/ChangePassword">更改密码</a></li>
            </ul>
        </div>
    </div>
</nav>
<!-- 导航 end -->
<!-- 占位空间 -->
<div class="zhanwei"></div>
<!-- 占位空间 end -->
<!-- 面包屑导航 -->
<div class="container-fluid nowp">
    <a href="/Home/IndexMobile">首页</a>
    <a href="/OrderSeatRec/CarListForOrder">订座</a>
    <a href="/OrderSeatRec/QryPersonal">我的乘车记录</a>
    <a href="/SysUser/ChangePassword">更改密码</a>
</div>
<!-- 面包屑导航 end -->
<script language="javascript" type="text/javascript">
    $(document).ready(function() {
        var changeOldpass = 1;
        var changeNewPw = 1;
        $("#OldPassword").change(function() {
            var oldPW = $("#OldPassword").val();
            var url = '@Url.Action("PasswordCheck", "SysUser")' + "?r=" + Math.random();
            $.get(url, { "oldPasswod": oldPW }, function(Check) {
                if (Check) {
                    $("#Show").html("<img src='../../Content/Img/btnOk.png' style=' height:19px; padding-bottom:0px;' />");
                    changeOldpass = 2;
                } else {
                    $("#Show").html("<img src='../../Content/Img/btnClose.png' style=' height:19px; padding-bottom:0px;'/>密码错误");
                }
            }, "json");
        })

        $("#password2").change(function() {
            var PW1 = $("#password1").val();
            var PW2 = $("#password2").val();
            if (PW1 == PW2) {
                $("#PWshow").html("<img src='../../Content/Img/btnOk.png' style=' height:19px; padding-bottom:0px;' />");
                changeNewPw = 3;
            } else {
                $("#PWshow").html("<img src='../../Content/Img/btnClose.png' style=' height:19px; padding-bottom:0px;'/>密码不一致");
            }
        });

        $("#BtnSave").click(function() {
            var PW = $("#password2").val();
            if (changeOldpass == 2 && changeNewPw == 3) {
                var url = '@Url.Action("ChangeNewPassword", "SysUser")' + "?R=" + Math.random();
                var data = { "password": PW };
                $.post(url, data, function(Check) {
                    if (Check) {
                        $("#ShowPWC").html("密码修改成功");
                    } else {
                        $("#ShowPWC").html("密码修改失败"); //失败不提示
                    }
                }, "json");
            }
        });
    });
    $(document).ready(function() {
        $("#BtnClear").click(function() {
            $("#OldPassword").val("");
            $("#password1").val("");
            $("#password2").val("");
        });
    });


    $(document).ready(function() {
        $("#aa").click(function() {
            location.href = "http://baidu.com";
        });
    });
</script>



<div class="container-fluid">
    <div class="dingzuo">
        <h2>更改密码</h2>
    </div>
    <div class="mimagenggai">
        <form action="">
            <p>
                姓&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;名：@Model.Name
            </p>
            <p>
                登录帐号：@Model.LoginCode
                </p>
                <div class="form-group">
                    @Html.TextBox("OldPassword", "", new { placeholder = "原密码", @class = "form-control input-lg", autocomplete = "off" })
                    <span id="Show"></span>
                </div>
                <div class="form-group">
                    @Html.TextBox("password1", "", new { placeholder = "新密码", @class = "form-control input-lg", autocomplete = "off" })
                </div>
                <div class="form-group">
                    @Html.TextBox("password2", "", new { placeholder = "确认密码", @class = "form-control input-lg", autocomplete = "off" })
                    <span id="PWshow"></span>
                </div>
                <div id="ShowPWC">
                </div>
                <div class="form-group">
                    <input type="button" value="确认" id="BtnSave" class="btn btn-block btn-lg btn-success" />
                    <input type="button" value="重置" id="BtnClear" class="btn btn-block btn-lg btn-success" />
                </div>
            </form>
        </div>
        <div class="text-center">
            <p class="text-center login_copy">
                重庆工程学院·版权所有
                <br>
                重庆惠科金渝光电 重庆市巴南区界石镇数码产业园
            </p>
        </div>
</div>

MvcApp/Views/SysUser/Details.cshtml
@using com.fxm.MVCHibernate.Domain
@model com.fxm.MVCHibernate.Domain.SysUser

@{
    ViewBag.Title = "用户详情";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="@Url.Content("~/Scripts/jquery.jqprint.js")" type="text/javascript"></script>
<script type="text/javascript">
    function PrintPage() {
        $("#printDiv").jqprint();
    }
</script>
@using (Html.BeginForm())
{
    <table cellspacing="0" cellpadding="0" style="vertical-align: top; width: 100%; border: 0;">
        <tr>
            <td class="contentPageTitle" style=" text-align:center;vertical-align:middle">
                用户详细信息
            </td>
        </tr>
        <tr>
            <td class="titleContentDivider"></td>
        </tr>
        <tr>
            <td height="30">
                <input type="button" value="返回列表" class="btn6" onclick="window.location='/SysUser/Index?pageIndex=1'" />
                <input type="button" value="打印" class="btn3" onclick="PrintPage()" />
            </td>
        </tr>
        <tr>
            <td>
                <div id="printDiv">
                    <fieldset>
                        <legend>用户</legend>
                        <div class="display-label">姓名</div>
                        <div class="display-field">@Html.DisplayFor(model => model.Name)</div>
                        <div class="display-label">登录账户</div>
                        <div class="display-field">@Html.DisplayFor(model => model.LoginCode)</div>
                        <div class="display-label">电话</div>
                        <div class="display-field">@Html.DisplayFor(model => model.Tel)</div>
                        <div class="display-label">状态</div>
                        <div class="display-field">
                            @if (Model.Status == 1)
                            {
                                @: 禁用
                            } else { 
                                @: 正常
                            }
                        </div>
                    </fieldset>
                    <fieldset>
                        <legend>所属角色</legend>
                        @Html.CheckBoxList("cblRole", (IEnumerable<SelectListItem>)ViewBag.cblItems, new { @disabled = "disabled" })
                    </fieldset>
                </div>
            </td>
        </tr>
    </table>
}

MvcApp/Views/SysUser/Login.cshtml
@model com.fxm.MVCHibernate.Domain.SysUser

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title>班车订座系统</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Login.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/MicrosoftAjax.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/MicrosoftMvcAjax.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.simplemodal.1.4.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.cookie.js")" type="text/javascript"></script>

    <script type="text/javascript">
        function CheckPage() {
            var loginName = $("#account").val(); 
            loginName = $.trim(loginName);
            if (loginName.length < 1) {
                document.getElementById("lblError").innerHTML = "用户名不能为空!";
                $("#account").focus();
                return false;
            }

            var pwd = $("#password").val(); 
            pwd = $.trim(pwd);
            if (pwd.length < 1) {
                document.getElementById("lblError").innerHTML = "密码不能为空!";
                $("#password").focus();
                return false;
            }
            return true;
        }

        function OnFailure(result) {
            document.getElementById("lblError").innerHTML = "系统错误,无法登录，请与管理员联系!"
        }

        function OnAJAXBegin() {
            if (CheckPage()) {
                $.modal("<img src='../Content/Img/loading.gif' alt=''></img>");
            }
        }

        function OnComplete(result) {
            $.modal.close(); 
            var returnValue = result.responseText; 
            if (returnValue == "0") {
                document.getElementById("lblError").innerHTML = "用户名或密码错误 或账号已停用!";
            }
            else {
                window.location.href = returnValue; 
            }
        }
        $(document).ready(function () {
            
            if ($.cookie("rmbUser") == "true") {
                $("#ck_rmbUser").attr("checked", true);
                $("#account").val($.cookie("account"));
                $("#password").val($.cookie("password"));
            }
        });

        //记住用户名密码
        function Save() {
            if ($("#ck_rmbUser").attr("checked")) {
                var str_username = $("#account").val();
                var str_password = $("#password").val();
                $.cookie("rmbUser", "true", { expires: 30 });
                $.cookie("account", str_username, { expires: 30 });
                $.cookie("password", str_password, { expires: 30 });
            }
            else {
                $.cookie("rmbUser", "false", { expire: -1 });
                $.cookie("account", "", { expires: -1 });
                $.cookie("password", "", { expires: -1 });
            }
        };
    </script>
</head>
<body>
    <center>
        <div class="divMain">

            <div class="divLoginArea">
                <div class="divMain000">

                </div>
                <div class="divAccount">
                    <div class="divInput">
                        @using (Ajax.BeginForm("Login", "SysUser", new AjaxOptions { OnBegin = "OnAJAXBegin", OnComplete = "OnComplete", OnFailure = "OnFailure" }))
                        {
                            <div class="divLoginLine">
                                <span>登录账号：</span>@Html.TextBox("account", "HK00001", new { @class = "textBox" })<br />
                            </div>
                            <div class="divLoginLine">
                                <span>密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码：</span>@Html.Password("password", "123", new { @class = "textBox" })
                            </div>
                            <div class="divLoginLine">
                                <span>记住登录账号和密码</span><input type="checkbox" id="ck_rmbUser" />
                            </div>
                            <div class="divButton divLoginLine">
                                <div id="divAjax">
                                    <input type="submit" id="btnLogin" class="btn3" value="登录" onclick="Save()" />
                                </div>
                                <div id="lblError" class="divNotice">
                                </div>
                            </div>
                        }
                    </div>
                </div>
                <div class="divPassword">
                </div>
            </div>
            <div class="divBottom">
                <div class="divWords">
                    © 重庆惠科金渝光电 渝ICP备16008032号 重庆市巴南区界石镇数码产业园 电话：023-81158888 传真：023-81158888
                </div>
            </div>
        </div>
    </center>
</body>
</html>

MvcApp/Views/SysUser/LoginMobile.cshtml
@{
    ViewBag.Title = "手机用户登录";
    Layout = "~/Views/Shared/_LayoutMobile.cshtml";
}
<script src="@Url.Content("~/Scripts/jquery-1.5.1.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/MicrosoftAjax.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/MicrosoftMvcAjax.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.simplemodal.1.4.1.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.cookie.js")" type="text/javascript"></script>

<script type="text/javascript">
    function CheckPage() {
        var loginName = $("#account").val();
        loginName = $.trim(loginName);
        if (loginName.length < 1) {
            document.getElementById("lblError").innerHTML = "用户名不能为空!";
            $("#account").focus();
            return false;
        }

        var pwd = $("#password").val();
        pwd = $.trim(pwd);
        if (pwd.length < 1) {
            document.getElementById("lblError").innerHTML = "密码不能为空!";
            $("#password").focus();
            return false;
        }
        return true;
    }

    function OnFailure(result) {
        document.getElementById("lblError").innerHTML = "系统错误,无法登录，请与管理员联系!"
    }

    function OnAJAXBegin() {
        if (CheckPage()) {
            $.modal("<img src='../Content/Img/loading.gif' alt=''></img>");
        }
    }

    function OnComplete(result) {
        $.modal.close();
        var returnValue = result.responseText;
        if (returnValue == "0") {
            document.getElementById("lblError").innerHTML = "用户名或密码错误 或账号已停用!";
        }
        else {
            //alert(returnValue);
            window.location.href = returnValue;
        }
    }
    $(document).ready(function () {
        if ($.cookie("rmbUser") == "true") {
            $("#ck_rmbUser").attr("checked", true);
            $("#account").val($.cookie("account"));
            $("#password").val($.cookie("password"));
        }
    });

    //记住用户名密码
    function Save() {
        if ($("#ck_rmbUser").attr("checked")) {
            var str_username = $("#account").val();
            var str_password = $("#password").val();
            $.cookie("rmbUser", "true", { expires: 30 }); 
            $.cookie("account", str_username, { expires: 30 });
            $.cookie("password", str_password, { expires: 30 });
        }
        else {
            $.cookie("rmbUser", "false", { expire: -1 });
            $.cookie("account", "", { expires: -1 });
            $.cookie("password", "", { expires: -1 });
        }
    };

</script>

<div class="login_container">
    <div class="login_body">

        <div class="login_title1">
            重庆惠科金渝光电
        </div>
        <h1 class="login_title">
            班车订座系统 <span>LOGIN</span>
        </h1>
        <p class="login_title_p">
            Dear user, log in to access the admin area!
        </p>
        @using (Ajax.BeginForm("Login", "SysUser", new AjaxOptions { OnBegin = "OnAJAXBegin", OnComplete = "OnComplete", OnFailure = "OnFailure" }))
        {
            <div class="form-group">
                <input type="text" placeholder="登录账号(员工工号或司机手机号)" class="form-control input-lg" name="account" id="account" autocomplete="off">
            </div>
            <div class="form-group">
                <input type="password" placeholder="登录密码" class="form-control input-lg" name="password" id="password" autocomplete="off">
            </div>
            <div class="form-group">
                记住登录账号和密码<input type="checkbox" id="ck_rmbUser" />
            </div>
            <div class="form-group">
                <input type="submit" value="登 录" onclick="Save()"  class="btn btn-block btn-lg btn-success">
            </div>
            <div id="lblError" class="divNotice">
            </div>
        }
    </div>
    <p class="text-center login_copy">
        重庆惠科金渝光电·版权所有
        <br>
        重庆市巴南区界石镇数码产业园
    </p>
</div>